version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
  api:
    build: .
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - DATABASE_URL=db
    depends_on:
      - db